# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54fca3f05269b4f25ba5e2114660c0a2f29c2a6da68636920239d332f22374350c8cdb16ad881566933945df6d131534528cfdb296514de8b39c8d510d2046c4

test:
  secret_key_base: 2a48eb9a6b4b67ec46c661ddc008e893a1cb5066294506575401a2d09eb76e5aba0b0f60e7fe7eda639c2d53357710f3035f7bc51f98811fe9a9d409ffaf4794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
